# Generated by Django 4.2.4 on 2023-08-28 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_card_bank_alter_account_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bank',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
