# Generated by Django 4.2.4 on 2023-08-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_card_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='bank',
        ),
    ]
