# Generated by Django 4.2.4 on 2023-08-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_card_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bank',
            field=models.CharField(default='Bank New America', max_length=40),
        ),
    ]
