# Generated by Django 4.2.4 on 2023-09-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_card_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=4),
        ),
    ]
