# Generated by Django 4.2.4 on 2023-08-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_images_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='created',
            new_name='created_at',
        ),
    ]
