# Generated by Django 4.2.4 on 2023-08-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_created_menuitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='date_edited',
        ),
    ]
